name: ci_gitlab

on:
  push:
    branches: master
    paths:
    - "examples/gitlab/**"
    - "modules/gitlab/**"
  workflow_dispatch:

jobs:
  ci:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout to repo
        uses: actions/checkout@v2
      - name: checkout starter configuration
        uses: actions/checkout@v2
        with:
          repository: "azure/caf-terraform-landingzones-starter"
      - name: azure cli login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: run test for gitlab
        run: |
          RANDOM=$(cat /dev/urandom | tr -dc "a-z" | fold -w 8 | head -n 1)
          export environment="ci_${RANDOM}"

          export GITLAB_TOKEN=${{ secrets.GITLAB_TOKEN }}

          export GITLAB_BASE_URL=${{ secrets.GITLAB_BASE_URL }}

          TENANT_ID=$(echo "${{ secrets.AZURE_CREDENTIALS }}" | jq -r "tenant_id")
          SUBSCRIPTION_ID=$(echo "${{ secrets.AZURE_CREDENTIALS }}" | jq -r "subscription_id")
          rover -lz /tf/caf/public/landingzones/caf_launchpad -launchpad -var-folder /tf/caf/configuration/${environment}/level0/launchpad -parallelism 30 -level level0 -env ${environment} -a apply

          rover -lz /tf/modules/examples/ -var-folder /tf/modules/examples/devops/providers/gitlab/new_project/  -level level1 -env ${environment} -a apply

          # call rover delete
